# Generated by Django 5.0.4 on 2024-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('synopsis', models.CharField(blank=True, max_length=2750, null=True)),
                ('genre', models.CharField(blank=True, max_length=160, null=True)),
                ('aired', models.CharField(blank=True, max_length=30, null=True)),
                ('episodes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('popularity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ranked', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
